version: '3.8'

services:
  php:
    container_name: blog4u_php-fpm
    build: ./php/
    ports:
      - '8081:8000'
    volumes:
      - ./:/var/www
    depends_on:
      - database

  database:
    container_name: blog4u_postgres
    image: postgres:14.1-alpine
    ports:
      - '5432:5432'
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres/data:/var/www/postgres/data

  adminer:
    image: adminer
    restart: always
    ports:
      - '8085:8080'

